### ISSUE TITLE
Yo-Kai Watch 4 FpsUnlocker Patch

### ISSUE THREAD

**Issue by SuperTavor** [masagrator/FPSLocker-Warehouse#148]
can you please add it?

**Comment by masagrator** [comment]
Added.

https://github.com/masagrator/FPSLocker-Warehouse/blob/main/SaltySD/plugins/FPSLocker/patches/010086C00AF7C000/C7DAB27F22ACD2ED.yaml

Game is using double buffer vsync, so it jumps between 30 and 60 FPS. It cannot be disabled with Window Sync option.

From my tests GPU is the most important factor here in getting stable 60 FPS. Tested 1963/998/1996 and it was almost stable 60 FPS in first cutscene which is a good benchmark, only one drop to 30 FPS for one second. GPU at 921 MHz was causing several drops to 30 FPS at that cutscene. Game is dynamically adjusting speed, so there are no slowdowns at 30 FPS.
