### ISSUE TITLE
Could you please make a patch for  Monster Hunter Rise that works with Japanese version (TID 0100559011740000)？

### ISSUE THREAD

**Issue by codeboy2202** [masagrator/FPSLocker-Warehouse#149]

**Comment by masagrator** [comment]
If you will send me `main` from exefs, I will look at it.

**Comment by codeboy2202** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by codeboy2202** [comment]
Thanks a lot for your reply.
Here is a main file extracted from NSP file (**version 15.0.1**) with Ryujinx. 
I'm not sure whether this is the file you need, if not please tell me.
https://drive.google.com/file/d/12zZYl-DjoKf6RZ_5GEqFtXCzWqN7lCFb/view?usp=sharing

**Comment by masagrator** [comment]
You must enable access to this file on gdrive for anybody with link.

**Comment by codeboy2202** [comment]
Sorry for that,please try again.

**Comment by masagrator** [comment]
For tests

https://github.com/masagrator/FPSLocker-Warehouse/blob/monhun/SaltySD/plugins/FPSLocker/patches/0100559011740000/5CE1FFBE4B433343.yaml

Yes, it uses the same offset as 15.0.0 western release. It seems JP version is now 1 update behind western release code wise?

**Comment by codeboy2202** [comment]
I have tested on my switch and it works!
Thank you very much!
