### ISSUE TITLE
Fate/Samurai Remnant 1.0.2

### ISSUE THREAD

**Issue by bilditup1** [masagrator/FPSLocker-Warehouse#230]
Is it possible to add a patch/profile for this? exefs/main is [here](https://drive.google.com/file/d/14-zGlI0QpCSAVzF3Tb53aDKuy9s-pgat/view?usp=sharing), hash [here](https://drive.google.com/file/d/1kjxPX2XnO6NuLdi6MA0LMxSfd1XMbz27/view?usp=sharing). No pressure obviously, I just miss 60fps since the update last month. Appreciated regardless!

**Comment by masagrator** [comment]
It's done for some time already, but nobody tested it yet since I did it remotely. :D

Confirm if it's working and FPSLocker shows that there are 3 buffers instead of 2 with some pic/screenshot.

[01003AE01AA76000.zip](https://github.com/masagrator/FPSLocker-Warehouse/files/13324502/01003AE01AA76000.zip)

**Comment by bilditup1** [comment]
Here we go:

![Fate_Samurai_Remnant_20231111_173504_00](https://github.com/masagrator/FPSLocker-Warehouse/assets/357902/072e9f86-bb77-4151-85ee-ec4596b9e416)
![Fate_Samurai_Remnant_20231111_173511_00](https://github.com/masagrator/FPSLocker-Warehouse/assets/357902/3a159f1e-4847-46c2-94ae-ad625ab8e7a5)
![Fate_Samurai_Remnant_20231111_172511_00](https://github.com/masagrator/FPSLocker-Warehouse/assets/357902/919f4bac-3176-495d-a2ae-1d1bf15524a8)
![Fate_Samurai_Remnant_20231111_172611_00](https://github.com/masagrator/FPSLocker-Warehouse/assets/357902/d11039c4-9e31-41bc-99f9-ec513f7d356c)
![Fate_Samurai_Remnant_20231111_173024_00](https://github.com/masagrator/FPSLocker-Warehouse/assets/357902/14195154-b5b9-48b2-8157-a516bc231723)
![Fate_Samurai_Remnant_20231111_172813_00](https://github.com/masagrator/FPSLocker-Warehouse/assets/357902/b2d463b5-76f0-4eb4-a6b2-959759038675)

Only now noticing that the watermark isn't removed, gonna have to look for a patch for that
ED: Remembered that that's due to dvr_patches, which I forgot to update. Anyway doesn't affect anything for us.
Otherwise, one thing I've noticed is that despite the patch: you have got to make sure the console is in handheld mode while plugged in (so, toggled via ReverseNX-RT) before you load the game, or possibly before you even get to the main title screen. Otherwise the game's 30fps cap isn't removed even in handheld mode.
