### ISSUE TITLE
【BOTW】Graphical issue happen when target fps set higher than 30.

### ISSUE THREAD

**Issue by codeboy2202** [masagrator/FPSLocker-Warehouse#276]
Really appreciate your work!
Here's the issue: A black flash appears on the screen when switching weapons with D-PAD if the target fps is set higher than 30 in FPSLocker which with the latest patch installed.

**Comment by ChanseyIsTheBest** [comment]
https://github.com/masagrator/FPSLocker-Warehouse/pull/275
In the pull-request for the patch this is one of the issues that isn't plan on being fixed.

**Comment by codeboy2202** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by masagrator** [comment]
As mentioned above. That's how game is coded and at higher FPS time distribution happens to make this show up. To fix this you would need to redesign code to wait for shader to finish, which I don't even know where is it and how to do that. This is also why you have black background issue in totk, but there for some reason time distribution is completely broken after some point where frames are rendered too fast. At least here we don't have black background being stuck.

You will get used to it. ;)
