### ISSUE TITLE
NARUTO X BORUTO Ultimate Ninja STORM CONNECTIONS 60fps

### ISSUE THREAD

**Issue by Paparey** [masagrator/FPSLocker-Warehouse#379]
NARUTO X BORUTO Ultimate Ninja STORM CONNECTIONS

**Describe what you want to modify**
My request is a 60 fps mod for these games. Resolution is 800p docked and 540p handheld.

**Describe many informations about this topic**
FPS drops often occur in game.Fps drops in different resolution levels, frequent pauses in games and for closes on the Snapdragon 680 processor

**Comment by masagrator** [comment]
This repo is not supporting emulators.
