### ISSUE TITLE
Add patch for Horizon Chase 2 1.6.3

### ISSUE THREAD

**Issue by mylesniutta** [masagrator/FPSLocker-Warehouse#420]
Hello! Is it possible to request an update for the latest version of Horizon Chase 2, v1.6.3?

BID: F80EEC237D0963EE
Update details in DBI: “Version 6”, (v393216)

Happy to provide a copy of the patch NSP if you need it as it wasn’t available through the “usual channels”.

Thank you!

**Comment by masagrator** [comment]
Just use Fast Scan in ue4cfgdumper and send here log file generated by it.

https://github.com/masagrator/UE4cfgdumper

**Comment by mylesniutta** [comment]
Thank you for your reply, please see attached :)
[F80EEC237D0963EE.log](https://github.com/user-attachments/files/15587588/F80EEC237D0963EE.log)

**Comment by mylesniutta** [comment]
Hey, for what it’s worth, I connected the dots and did a “find and replace all” for the values according to that log file. Uploaded to my Switch and applied the patch, restarted the game, and getting a silky smooth 60FPS.

YAML attached in the hope it saves you some time to add to the warehouse.

Thanks for a brilliant bit of software!
[F80EEC237D0963EE.yaml.txt](https://github.com/user-attachments/files/15594767/F80EEC237D0963EE.yaml.txt)

**Comment by masagrator** [comment]
Patch added. Thanks for log file.
