### ISSUE TITLE
EA Sports FC 24 1.59.6eaf error 0x15

### ISSUE THREAD

**Issue by patitocarei** [masagrator/FPSLocker-Warehouse#456]
Hi, thanks for the work.
My game says 0x15 error and doesn't allow creating a configuration file. I have SAME version, check images and thanks! 
Sorry for my english.
![2](https://github.com/masagrator/FPSLocker-Warehouse/assets/85491484/18c406c6-e048-43ae-8560-7de58013b279)

**Comment by patitocarei** [comment]
Switch Os Version 18.0.1, Atmosphere 1.7.0

**Comment by masagrator** [comment]
You didn't update FPSLocker overlay. Update to newest version.
