### ISSUE TITLE
60fps patch for "Xenoblade Chronicles 2"

### ISSUE THREAD

**Issue by Soneoylys** [masagrator/FPSLocker-Warehouse#578]
Seems fpslocker alone will not unlock 30fps cap and there's no patch avaliable in this repo, is there any known patches for older version or WIP?
If so, I may can help finding new offsets & etc.

**Comment by Soneoylys** [comment]
Just noticed this game is referring itself as Xenoblade2 not Xenoblade Chronicles 2, and the title ID/version is not matching up with database, I set automatic update enabled so it should be latest version for me (2.0.2)

I wonder if that's an error or this game have different region with different binary and if that also makes difference in patching (different offsets)

![eShop_20241108_185211_00](https://github.com/user-attachments/assets/41a3937f-ac7a-480f-9269-73ebfeaa626a)
![ゼノブレイド２_20241108_185741_00](https://github.com/user-attachments/assets/02ccf6f1-060a-4587-a005-13648398fb2a)

**Comment by masagrator** [comment]
What a coincidence. I plan to release it this weekend, though it won't be tested thoroughly.

**Comment by masagrator** [comment]
And there are 2 XC2 releases - global and Japanese.

**Comment by Soneoylys** [comment]
very funny is i purchased this game with global eshop account, and dlc in japan eshop, my switch system set to japan, and it downloaded the japan version of the game... not big deal tho

anyway, i'd like to test the patch if needed, in fact i just put the binary in disassembler 5min before you reply, thanks for your work!

**Comment by masagrator** [comment]
Added patch for Western release. You can send me main so I can port it to Japanese release

**Comment by Soneoylys** [comment]
dumped Program #0 section with game version 2.0.2, check attached zip file

[ゼノブレイド２ 2.0.2 [0100F3400332C800][v917504][UPD].zip](https://github.com/user-attachments/files/17691194/2.0.2.0100F3400332C800.v917504.UPD.zip)

![Album_20241108_193037_00](https://github.com/user-attachments/assets/276847e1-1123-4aec-9073-b1839513e009)

**Comment by Soneoylys** [comment]
afaik, there's only one slight offset difference between this two versions:
```
ALL_FPS:
  -
    type: evaluate_write
    address: [MAIN, 0xB74BC0] # 0xB74BF0 for international version
    value_type: uint32
    value: ["VSYNC_TARGET", "VSYNC_TARGET"]
```

~~I'll test and see if it works once I got home.~~
update: It doesn't work, maybe there's more offset differences, I do not own a copy of international version of Xenoblade2 thus I cannot figure what else are different, sorry.

**Comment by masagrator** [comment]
You having Japanese release is enough. Just send me "main" from exefs

**Comment by Soneoylys** [comment]
it's inside the zip file I attached early on (10MiB), github only accept attachment files in some known extensions

![image](https://github.com/user-attachments/assets/a3592ed2-95ea-48dc-a307-59d1dab06f8d)

> dumped Program #0 section with game version 2.0.2, check attached zip file
> 
> [ゼノブレイド２ 2.0.2 [0100F3400332C800][v917504][UPD].zip](https://github.com/user-attachments/files/17691194/2.0.2.0100F3400332C800.v917504.UPD.zip)

**Comment by masagrator** [comment]
Ah, sorry. Didn't see that 😅

**Comment by masagrator** [comment]
[Xenoblade2Test.zip](https://github.com/user-attachments/files/17692065/Xenoblade2Test.zip)

For tests. Only thing I am not sure if it will work is blocking cutscenes to 30 FPS. So as long as that works, everything else should work the same as patch for Western release.

**Comment by Soneoylys** [comment]
The framerate is locked correctly in cutscene, I played around in different scenes and can confirm patch is fully working, thanks!
![ゼノブレイド２_20241111_012221_00](https://github.com/user-attachments/assets/3a4095ba-80f8-45cf-b183-7ed7a92ffea5)
![ゼノブレイド２_20241111_012305_00](https://github.com/user-attachments/assets/08051ccf-1501-4203-93c6-becc0aa743c4)
