### ISSUE TITLE
Yakuza Kiwami 1.0.1

### ISSUE THREAD

**Issue by WXDFever** [masagrator/FPSLocker-Warehouse#632]
Hello. I noticed Yakuz Kiwami updated game patch 1.0.1 lately. The build ID should be changed to AE90FD64E7B2FE1E, but for the configs file, it's still 53F407A2CFBF5202, is it a mistake? Thanks in advance

**Comment by masagrator** [comment]
Yes, that was a mistake. Fixed. Thanks.
