### ISSUE TITLE
The Legend of Zelda: Tears of the Kingdom 1.2.1 Patch Issue

### ISSUE THREAD

**Issue by SamuelTerrance** [masagrator/FPSLocker-Warehouse#674]
I am using the patch 1.2.1 of 'Legend of Zelda: Tears of the Kingdom' and it will prompt that the software has encountered an error and has been closed. Delete it to run normally. Currently, it is the latest atmospheric 18.0.0 and the latest firmware 19.0.1

**Comment by SamuelTerrance** [comment]
> I am using the patch 1.2.1 of 'Legend of Zelda: Tears of the Kingdom' and it will prompt that the software has encountered an error and has been closed. Delete it to run normally. Currently, it is the latest atmospheric 18.0.0 and the latest firmware 19.0.1

A patch file named main.npdm has already been placed in the directory atmosphere/contents/0100F2C0115B6000/extfs/

**Comment by SamuelTerrance** [comment]
> > I am using the patch 1.2.1 of 'Legend of Zelda: Tears of the Kingdom' and it will prompt that the software has encountered an error and has been closed. Delete it to run normally. Currently, it is the latest atmospheric 18.0.0 and the latest firmware 19.0.1
> 
> A patch file named main.npdm has already been placed in the directory atmosphere/contents/0100F2C0115B6000/extfs/

Still prompt that the software has encountered an error and has been closed

**Comment by masagrator** [comment]
> atmosphere/contents/0100F2C0115B6000/extfs

It's "exefs", not "extfs"

**Comment by SamuelTerrance** [comment]
thanks
